development:
  adapter: postgresql
  encoding: unicode
  database: oe_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: oe_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: oe_production
  pool: 5
